pg_version = "17.0"
assume_in_transaction = true
excluded_rules = [
  "ban-concurrent-index-creation-in-transaction", # This is checked in .mise-tasks/lint/migrations.sh
  "prefer-robust-stmts",
  "ban-drop-not-null",
  "constraint-missing-not-valid",
]
[upload_to_github]
fail_on_violations = true
