pg_version = "17.0"
assume_in_transaction = true
excluded_rules = [
  "require-timeout-settings",
  "ban-concurrent-index-creation-in-transaction", # This is checked in .mise-tasks/lint/migrations.sh
  "prefer-robust-stmts",
  "ban-drop-not-null",
  "constraint-missing-not-valid",
  "adding-foreign-key-constraint",
  "disallowed-unique-constraint",
  "ban-drop-column",
  "adding-required-field",
  "adding-field-with-default",
]
[upload_to_github]
fail_on_violations = true
