name: Chromatic

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: Check for elements changes
    runs-on: ubicloud-standard-4
    permissions:
      contents: read
      pull-requests: read
    outputs:
      elements: ${{ steps.gates.outputs.elements }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        name: Check for changed packages
        id: filter
        with:
          filters: .github/filters.yaml
      - id: gates
        name: Set outputs
        run: |
          if [[ "${{ steps.filter.outputs.elements }}" == "true" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "elements=true" >> $GITHUB_OUTPUT
            echo "Elements jobs will run."
          else
            echo "Elements jobs will be skipped."
          fi

  chromatic:
    name: Visual regression tests
    runs-on: ubicloud-standard-4
    needs: changes
    steps:
      - name: Skip if no elements changes exist
        if: ${{ needs.changes.outputs.elements != 'true' }}
        run: echo "No elements changes detected â€” skipping chromatic job."

      - name: Checkout
        if: ${{ needs.changes.outputs.elements == 'true' }}
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Mise
        if: ${{ needs.changes.outputs.elements == 'true' }}
        uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0
        with:
          install: true
          cache: true
          env: false

      - name: Prepare GitHub Actions environment
        if: ${{ needs.changes.outputs.elements == 'true' }}
        run: mise run github

      - name: Cache PNPM
        if: ${{ needs.changes.outputs.elements == 'true' }}
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}

      - name: Install dependencies
        if: ${{ needs.changes.outputs.elements == 'true' }}
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        if: ${{ needs.changes.outputs.elements == 'true' }}
        run: pnpm build-storybook
        working-directory: elements
        env:
          STORYBOOK_CHROMATIC: "true"

      - name: Run Chromatic
        if: ${{ needs.changes.outputs.elements == 'true' }}
        uses: chromaui/action@07791f8243f4cb2698bf4d00426baf4b2d1cb7e0 # v13.3.5
        with:
          workingDir: elements
          storybookBuildDir: storybook-static
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: main
          onlyChanged: true

      - name: Prune PNPM store
        if: ${{ needs.changes.outputs.elements == 'true' && success() }}
        run: pnpm store prune
